---
title: "Real Estate Price Prediction Using Ordinary Lease Squares Regression (n > p)"
author: "Bedrock Stat Analytics"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: 
  pdf_document:
    fig_caption: yes
  pandoc_args: [
      "--number-sections",
      "--number-offset=1"
    ]

header-includes:
- \usepackage{pdflscape}
- \usepackage{booktabs}
- \usepackage{longtable}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}

params:
  dat_data: NA
  dat_file: NA
---

```{r include=F}
knitr::opts_chunk$set(comment = NA)
```


```{r,echo=F,warning=F,message=F, error=F}
library(caret)
library(knitr)
library(DMwR)
library(prettyR)
library(xtable)
library(kableExtra)
library(broom)
```

```{r,echo=F}
dat <- params$dat_data
name <- params$dat_file
``` 

```{r cache=F, echo=F}
read_chunk('ols_model.R')
read_chunk('help_functions.R')
```
`r sprintf("Using Data file - %s.",name) `

```{r, echo=FALSE}
# Load data file
dat <- params$dat_data
# read chunk (does not run code)
dataIn <- dat
dataIn <- dataIn[ , !names(dataIn) %in% c("MezzanineYes1")]
indx <- sapply(dataIn, is.factor)
dataIn[indx] <- lapply(dataIn[indx], function(x) as.numeric(x))
```


# Summary Statistics
```{r  descriptive_stat, results='asis', echo = F, message=F}
```
```{r  descriptive_stat_pdf_table, results='asis', echo = F, message=F}
# Summary of unscaled predictor (x) variables 
```
```{r standardize_xy, echo=F}
# standardiize xy variables
```

```{r ols_preprocess, echo=FALSE}
# Pre-process
```

# Correlations Between Predictors
```{r ols_cor_plot, echo=F, fig.height=12,fig.width=12}
# Plot the correlations between predictors
```

# Variable Importance
```{r  make_ols_model, echo = F,fig.width=5,fig.height=5}
```
```{r var_importance, echo=F,fig.height=10,fig.width=10}
# get varible importance
```
```{r  best_model, echo = F}
```


# Model Prediction
```{r predict_price, echo = F, warning = F}
```
```{r predict_price_pdf, results = 'asis', echo = F, warning = F}
```


# Standardized Model Coefficients
```{r  ols_coeff, echo = F}
```
```{r  ols_coeff_pdf_table, results ='asis', echo = F}
```


\blandscape 
```{r, echo=FALSE}
knitr::kable(dat, 
             format = "latex",
             booktabs = TRUE,
             caption = "APPENDIX : Raw data table") %>%
kableExtra::kable_styling(latex_options = c("repeat_header"), font_size = 7) 
``` 
\elandscape 
